version: '3.4'

services:
  carsapi_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5433:5432" 
    networks:
      - shared_carsapi_net
    volumes:
      - dbdata:/var/lib/postgresql/data

  carsapi_minio:
    container_name: minio
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: zg2cEegUG0aHRfBqp8xc
      MINIO_ROOT_PASSWORD: zfZFGKezj6OYM1kjDvw1pMOWhZvEUxkoqNulHAzq
    command: server --console-address ":9001" /data
    networks:
      - shared_carsapi_net
    volumes:
      - minio_storage:/data

  carsapi_web:
    ports:
      - "10000:8080"
    networks:
      - shared_carsapi_net
    env_file:
      - web.env

volumes:
  dbdata:
  minio_storage:
  
networks:
  shared_carsapi_net:
    name: carsapi
    driver: bridge