version: '3.4'

services:
  carsapi_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5433:5432" 
    networks:
      - shared_carsapi_net
    volumes:
      - dbdata:/var/lib/postgresql/data

  carsapi_web:
    ports:
      - "10000:8080"
    networks:
      - shared_carsapi_net
    env_file:
      - web.env

volumes:
  dbdata:
  
networks:
  shared_carsapi_net:
    name: carsapi
    driver: bridge